function sampleArray = uniprofile(d,newx, newy)
% this function is to get the intensity value of a image along the ROI
% lines
% d is the cell array generated by bfopen
% newx is the x coordinate of the ROI line
% newy is the y coordinate of the ROI line
% sampleArray has the dimension of length of ROI line, number of ROI lines,
% and number of channels

sampleNum = size(newx,1);
nchannel = size(d{1},1);
sampleCellArray = cell(nchannel, sampleNum);
sampleLength = zeros(sampleNum, 1);
for j = 1:nchannel
    data = d{1}{j,1};
    for i = 1:sampleNum
        lineLength = floor(sqrt((newx(i,1) - newx(i, 2))^2+ (newy(i,1) - newy(i,2))^2));
        sampleLine = improfile(data, newx(i,:), newy(i,:),lineLength); 
        % to make sure the generated measurement is the same length as the
        % line, instead of the default setting of improfile function
        sampleCellArray{j,i} = sampleLine;
        sampleLength(i) = lineLength;
        % plot(sampleLine)
        % hold on
    end
end

sampleArray = zeros(min(sampleLength),sampleNum,nchannel);

for j = 1:nchannel
    for i = 1:sampleNum
        sampleArray(:,i,j) = sampleCellArray{j, i}(1:min(sampleLength));
    end
end

figure,
for j = 1:nchannel
    plot(mean(sampleArray(:, :, j),2))
    hold on
end
legend
end